# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('like_nums', models.ImageField(default=0, upload_to='', verbose_name='点赞数')),
            ],
            options={
                'verbose_name_plural': '我的博客',
                'db_table': 'b_blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '文章类别',
                'db_table': 'b_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('b_comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog', verbose_name='评论的博客')),
            ],
            options={
                'verbose_name_plural': '博客评论',
                'db_table': 'b_comment',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='文章标签')),
            ],
            options={
                'verbose_name_plural': '文章标签',
                'db_table': 'b_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='headimages')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('profession', models.CharField(max_length=64, verbose_name='职业')),
                ('native_place', models.CharField(max_length=256, verbose_name='籍贯')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
                ('ip', models.CharField(max_length=32, verbose_name='登录地址')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次登录时间')),
                ('login_nums', models.IntegerField(default=0, verbose_name='登录次数')),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': '用户管理',
                'db_table': 'b_user',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='u_comm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='个人分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='app.Tag', verbose_name='文章标签'),
        ),
        migrations.AddField(
            model_name='blog',
            name='u_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
