# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_nums',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
