# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(upload_to='headimages'),
        ),
    ]
