# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190116_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 3, 49, 25, 311594, tzinfo=utc), verbose_name='登录时间'),
        ),
    ]
